version: '3.8'
services:
  notabee_mysql:
    container_name: notabee_mysql
    image: mysql:5.7
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./notabee_mysql:/var/lib/notabee_mysql
    
  rails:
    build: .
    depends_on:
      - vite
      - notabee_mysql
    entrypoint: ./docker-rails.sh
    environment:
      RAILS_ENV: development
      VITE_RUBY_HOST: vite
    ports:
      - "3000:3000"
    volumes:
      - .:/app
  vite:
    build: .
    entrypoint: ./docker-vite.sh
    environment:
      DEBUG: '*vite*'
      RAILS_ENV: development
      VITE_RUBY_HOST: 0.0.0.0
    ports:
      - "3036:3036"
    volumes:
      - .:/app
      - /app/node_modules




